#!/usr/bin/env python3
"""Create per-tool wrapper scripts that exec `wabt <subcommand>`.

The legacy test harness in test/run-tests.py expects per-tool binaries
(wat2wasm, wasm2wat, ...). The current zig branch ships a single `wabt`
binary with subcommands. This script generates thin shims so the legacy
harness can keep working unchanged.

Usage:
    python3 scripts/install_cli_shims.py                # default: zig-out/bin
    python3 scripts/install_cli_shims.py --bin DIR      # custom dir
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Map legacy tool name -> wabt subcommand. Tools that no longer exist on
# the zig branch (wasm-interp, wasm2c) are mapped to None and emitted as
# "missing tool" stubs that always exit 1, so the harness can locate them
# and tests using them fail explicitly (and can be SKIP-marked individually).
SHIMS: dict[str, str | None] = {
    "wat2wasm": "parse",
    "wasm2wat": "print",
    "wasm-validate": "validate",
    "wasm-objdump": "objdump",
    "wasm-strip": "strip",
    "wast2json": "json-from-wast",
    "wasm-decompile": "decompile",
    "wasm-stats": "stats",
    "wat-desugar": "desugar",
    "spectest-interp": "spectest",
    "wasm-interp": None,
    "wasm2c": None,
}


def write_unix_shim(path: Path, wabt: Path, subcommand: str | None, tool: str) -> None:
    if subcommand is None:
        script = (
            f"#!/bin/sh\n"
            f"# Auto-generated stub: '{tool}' is not available on the zig branch.\n"
            f'echo "{tool}: not implemented in this build" >&2\n'
            f"exit 1\n"
        )
    else:
        script = f"""#!/bin/sh
# Auto-generated by scripts/install_cli_shims.py
exec "{wabt}" {subcommand} "$@"
"""
    path.write_text(script)
    path.chmod(0o755)


def write_windows_shim(path: Path, wabt: Path, subcommand: str | None, tool: str) -> None:
    if subcommand is None:
        script = (
            "@echo off\r\n"
            f"REM Auto-generated stub: '{tool}' is not available on the zig branch.\r\n"
            f'echo {tool}: not implemented in this build 1>&2\r\n'
            "exit /b 1\r\n"
        )
    else:
        # cmd.exe batch wrapper. %~dp0 expands to the script's own directory so
        # the shim resolves wabt.exe relative to itself.
        script = (
            "@echo off\r\n"
            "REM Auto-generated by scripts\\install_cli_shims.py\r\n"
            f'"{wabt}" {subcommand} %*\r\n'
        )
    path.write_text(script)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--bin", type=Path,
                   default=Path("zig-out/bin"),
                   help="Directory containing the wabt binary; shims are "
                        "written into the same dir (default: zig-out/bin).")
    args = p.parse_args()

    is_windows = os.name == "nt"
    wabt_name = "wabt.exe" if is_windows else "wabt"
    wabt = (args.bin / wabt_name).resolve()
    if not wabt.is_file():
        sys.exit(f"wabt not found: {wabt}\nRun `zig build` first.")

    bin_dir = args.bin.resolve()
    written = []
    for tool, subcmd in SHIMS.items():
        if is_windows:
            shim = bin_dir / f"{tool}.cmd"
            write_windows_shim(shim, wabt, subcmd, tool)
        else:
            shim = bin_dir / tool
            write_unix_shim(shim, wabt, subcmd, tool)
        written.append(shim.name)

    print(f"Wrote {len(written)} shims to {bin_dir}: {', '.join(sorted(written))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
