//! C source code writer for WebAssembly modules.
//!
//! Generates C header (.h) and implementation (.c) content from Module IR,
//! compatible with the wasm2c runtime.

const std = @import("std");
const types = @import("types.zig");
const Mod = @import("Module.zig");

pub const WriteError = error{OutOfMemory};

/// Generate C header (.h) content for a wasm module.
pub fn writeHeader(allocator: std.mem.Allocator, module: *const Mod.Module, module_name: []const u8) WriteError![]u8 {
    var w = CW{ .allocator = allocator, .buf = .empty };
    errdefer w.buf.deinit(allocator);
    try w.emitHeader(module, module_name);
    return w.buf.toOwnedSlice(allocator);
}

/// Generate C implementation (.c) content for a wasm module.
pub fn writeSource(allocator: std.mem.Allocator, module: *const Mod.Module, module_name: []const u8) WriteError![]u8 {
    var w = CW{ .allocator = allocator, .buf = .empty };
    errdefer w.buf.deinit(allocator);
    try w.emitSource(module, module_name);
    return w.buf.toOwnedSlice(allocator);
}

fn valTypeToCType(vt: types.ValType) []const u8 {
    return switch (vt) {
        .i32 => "uint32_t",
        .i64 => "uint64_t",
        .f32 => "float",
        .f64 => "double",
        .v128 => "wasm_rt_v128_t",
        .funcref => "wasm_rt_funcref_t",
        .externref => "wasm_rt_externref_t",
        else => "uint32_t",
    };
}

fn resolveSig(module: *const Mod.Module, decl: Mod.FuncDeclaration) types.FuncType {
    switch (decl.type_var) {
        .index => |ti| {
            if (ti != types.invalid_index and ti < module.module_types.items.len) {
                switch (module.module_types.items[ti]) {
                    .func_type => |ft| return .{ .params = ft.params, .results = ft.results },
                    else => {},
                }
            }
        },
        .name => {},
    }
    return decl.sig;
}

fn getFuncSig(module: *const Mod.Module, index: u32) types.FuncType {
    if (index >= module.funcs.items.len) return .{};
    return resolveSig(module, module.funcs.items[index].decl);
}

const CW = struct {
    allocator: std.mem.Allocator,
    buf: std.ArrayList(u8),

    // ── Main emitters ───────────────────────────────────────────────────

    fn emitHeader(self: *CW, module: *const Mod.Module, name: []const u8) WriteError!void {
        try self.append("/* Generated by wabt-zig */\n");

        // Include guard
        try self.append("#ifndef ");
        try self.appendUpperName(name);
        try self.append("_H_\n#define ");
        try self.appendUpperName(name);
        try self.append("_H_\n\n");

        try self.append("#include \"wasm-rt.h\"\n\n");
        try self.append("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

        // Types
        if (module.module_types.items.len > 0) {
            try self.append("/* Types */\n");
            for (module.module_types.items, 0..) |entry, i| {
                switch (entry) {
                    .func_type => |ft| {
                        try self.append("typedef ");
                        try self.writeCReturnType(ft.results);
                        try self.append(" (*wasm_rt_func_type_");
                        try self.writeU32(@intCast(i));
                        try self.append(")(");
                        try self.writeCParams(ft.params);
                        try self.append(");\n");
                    },
                    else => {},
                }
            }
            try self.appendByte('\n');
        }

        // Exports
        if (module.exports.items.len > 0) {
            try self.append("/* Exports */\n");
            for (module.exports.items) |exp| {
                switch (exp.kind) {
                    .func => {
                        const sig = getFuncSig(module, exp.var_.index);
                        try self.append("extern ");
                        try self.writeCReturnType(sig.results);
                        try self.appendByte(' ');
                        try self.append(name);
                        try self.appendByte('_');
                        try self.appendSanitized(exp.name);
                        try self.appendByte('(');
                        try self.writeCParams(sig.params);
                        try self.append(");\n");
                    },
                    .memory => {
                        try self.append("extern wasm_rt_memory_t* ");
                        try self.append(name);
                        try self.appendByte('_');
                        try self.appendSanitized(exp.name);
                        try self.append("(void);\n");
                    },
                    else => {},
                }
            }
            try self.appendByte('\n');
        }

        // Init/Free
        try self.append("/* Init/Free */\n");
        try self.append("extern void ");
        try self.append(name);
        try self.append("_init(void);\nextern void ");
        try self.append(name);
        try self.append("_free(void);\n\n");

        try self.append("#ifdef __cplusplus\n}\n#endif\n\n");
        try self.append("#endif /* ");
        try self.appendUpperName(name);
        try self.append("_H_ */\n");
    }

    fn emitSource(self: *CW, module: *const Mod.Module, name: []const u8) WriteError!void {
        try self.append("/* Generated by wabt-zig */\n");
        try self.append("#include \"");
        try self.append(name);
        try self.append(".h\"\n\n");

        // Memory
        if (module.memories.items.len > 0) {
            try self.append("/* Memory */\n");
            for (0..module.memories.items.len) |i| {
                try self.append("static wasm_rt_memory_t memory_");
                try self.writeU32(@intCast(i));
                try self.append(";\n");
            }
            try self.appendByte('\n');
        }

        // Globals (defined only)
        const gstart = module.num_global_imports;
        if (gstart < module.globals.items.len) {
            try self.append("/* Globals */\n");
            for (module.globals.items[gstart..], 0..) |global, i| {
                try self.append("static ");
                try self.append(valTypeToCType(global.type.val_type));
                try self.append(" global_");
                try self.writeU32(@intCast(i));
                try self.append(" = 0;\n");
            }
            try self.appendByte('\n');
        }

        // Init
        try self.append("/* Init */\nvoid ");
        try self.append(name);
        try self.append("_init(void) {\n");
        for (module.memories.items, 0..) |mem, i| {
            try self.append("  wasm_rt_allocate_memory(&memory_");
            try self.writeU32(@intCast(i));
            try self.append(", ");
            try self.writeU64(mem.type.limits.initial);
            try self.append(", ");
            if (mem.type.limits.has_max) {
                try self.writeU64(mem.type.limits.max);
            } else {
                try self.append("65536");
            }
            try self.append(", 0);\n");
        }
        try self.append("}\n\n");

        // Free
        try self.append("/* Free */\nvoid ");
        try self.append(name);
        try self.append("_free(void) {\n");
        for (0..module.memories.items.len) |i| {
            try self.append("  wasm_rt_free_memory(&memory_");
            try self.writeU32(@intCast(i));
            try self.append(");\n");
        }
        try self.append("}\n\n");

        // Functions (stubs for defined functions)
        const fstart = module.num_func_imports;
        if (fstart < module.funcs.items.len) {
            try self.append("/* Functions (stubs) */\n");
            for (module.funcs.items[fstart..], 0..) |_, i| {
                const idx = fstart + @as(u32, @intCast(i));
                const sig = getFuncSig(module, idx);
                try self.writeCReturnType(sig.results);
                try self.appendByte(' ');
                try self.append(name);
                try self.append("_func_");
                try self.writeU32(idx);
                try self.appendByte('(');
                try self.writeCParams(sig.params);
                try self.append(") {\n  /* TODO: instruction translation */\n}\n\n");
            }
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    fn a(self: *CW) std.mem.Allocator {
        return self.allocator;
    }

    fn append(self: *CW, s: []const u8) WriteError!void {
        try self.buf.appendSlice(self.a(), s);
    }

    fn appendByte(self: *CW, b: u8) WriteError!void {
        try self.buf.append(self.a(), b);
    }

    fn writeU32(self: *CW, v: u32) WriteError!void {
        var tmp: [16]u8 = undefined;
        const result = std.fmt.bufPrint(&tmp, "{d}", .{v}) catch unreachable;
        try self.append(result);
    }

    fn writeU64(self: *CW, v: u64) WriteError!void {
        var tmp: [24]u8 = undefined;
        const result = std.fmt.bufPrint(&tmp, "{d}", .{v}) catch unreachable;
        try self.append(result);
    }

    fn writeCReturnType(self: *CW, results: []const types.ValType) WriteError!void {
        if (results.len == 0) {
            try self.append("void");
        } else {
            try self.append(valTypeToCType(results[0]));
        }
    }

    fn writeCParams(self: *CW, params: []const types.ValType) WriteError!void {
        if (params.len == 0) {
            try self.append("void");
        } else {
            for (params, 0..) |p, i| {
                if (i > 0) try self.append(", ");
                try self.append(valTypeToCType(p));
            }
        }
    }

    fn appendUpperName(self: *CW, name: []const u8) WriteError!void {
        for (name) |c| {
            if (std.ascii.isAlphanumeric(c)) {
                try self.appendByte(std.ascii.toUpper(c));
            } else {
                try self.appendByte('_');
            }
        }
    }

    fn appendSanitized(self: *CW, name: []const u8) WriteError!void {
        for (name) |c| {
            if (std.ascii.isAlphanumeric(c) or c == '_') {
                try self.appendByte(c);
            } else {
                try self.appendByte('_');
            }
        }
    }
};

// ── Tests ───────────────────────────────────────────────────────────────

test "empty module header has guard" {
    var module = Mod.Module.init(std.testing.allocator);
    defer module.deinit();
    const hdr = try writeHeader(std.testing.allocator, &module, "test_mod");
    defer std.testing.allocator.free(hdr);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "Generated by wabt-zig") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "#ifndef TEST_MOD_H_") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "#define TEST_MOD_H_") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "#endif") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "test_mod_init") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "test_mod_free") != null);
}

test "header with memory" {
    const alloc = std.testing.allocator;
    var module = Mod.Module.init(alloc);
    defer module.deinit();
    try module.memories.append(alloc, .{ .type = .{ .limits = .{ .initial = 1, .has_max = true, .max = 256 } } });
    try module.exports.append(alloc, .{ .name = "memory", .kind = .memory, .var_ = .{ .index = 0 } });
    const hdr = try writeHeader(alloc, &module, "mod");
    defer alloc.free(hdr);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "wasm_rt_memory_t") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "mod_memory") != null);
}

test "header with function type" {
    const alloc = std.testing.allocator;
    var module = Mod.Module.init(alloc);
    defer module.deinit();
    try module.module_types.append(alloc, .{ .func_type = .{ .params = &.{}, .results = &.{} } });
    const hdr = try writeHeader(alloc, &module, "mod");
    defer alloc.free(hdr);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "typedef") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "wasm_rt_func_type_0") != null);
}

test "header with export" {
    const alloc = std.testing.allocator;
    var module = Mod.Module.init(alloc);
    defer module.deinit();
    try module.funcs.append(alloc, .{});
    try module.exports.append(alloc, .{ .name = "run", .kind = .func, .var_ = .{ .index = 0 } });
    const hdr = try writeHeader(alloc, &module, "w2c");
    defer alloc.free(hdr);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "extern") != null);
    try std.testing.expect(std.mem.indexOf(u8, hdr, "w2c_run") != null);
}

test "source with memory" {
    const alloc = std.testing.allocator;
    var module = Mod.Module.init(alloc);
    defer module.deinit();
    try module.memories.append(alloc, .{ .type = .{ .limits = .{ .initial = 1, .has_max = true, .max = 256 } } });
    const src = try writeSource(alloc, &module, "mod");
    defer alloc.free(src);
    try std.testing.expect(std.mem.indexOf(u8, src, "static wasm_rt_memory_t memory_0") != null);
    try std.testing.expect(std.mem.indexOf(u8, src, "wasm_rt_allocate_memory") != null);
    try std.testing.expect(std.mem.indexOf(u8, src, "wasm_rt_free_memory") != null);
}

test "source with global" {
    const alloc = std.testing.allocator;
    var module = Mod.Module.init(alloc);
    defer module.deinit();
    try module.globals.append(alloc, .{ .type = .{ .val_type = .i32, .mutability = .mutable } });
    const src = try writeSource(alloc, &module, "mod");
    defer alloc.free(src);
    try std.testing.expect(std.mem.indexOf(u8, src, "static uint32_t global_0") != null);
}

test "source with function stub" {
    const alloc = std.testing.allocator;
    var module = Mod.Module.init(alloc);
    defer module.deinit();
    try module.funcs.append(alloc, .{});
    const src = try writeSource(alloc, &module, "mod");
    defer alloc.free(src);
    try std.testing.expect(std.mem.indexOf(u8, src, "mod_func_0") != null);
    try std.testing.expect(std.mem.indexOf(u8, src, "TODO: instruction translation") != null);
}

test "valTypeToCType mapping" {
    try std.testing.expectEqualStrings("uint32_t", valTypeToCType(.i32));
    try std.testing.expectEqualStrings("uint64_t", valTypeToCType(.i64));
    try std.testing.expectEqualStrings("float", valTypeToCType(.f32));
    try std.testing.expectEqualStrings("double", valTypeToCType(.f64));
    try std.testing.expectEqualStrings("wasm_rt_funcref_t", valTypeToCType(.funcref));
    try std.testing.expectEqualStrings("wasm_rt_externref_t", valTypeToCType(.externref));
}
