//! PetStore — a `wasi:http@0.3.0` service implementing the TypeSpec petstore
//! sample (microsoft/typespec petstore.tsp) over an in-memory store seeded
//! with example pets and toys.
//!
//! Routes:
//!   GET    /pets                 -> { items: Pet[] }
//!   POST   /pets                 -> created Pet            (body: Pet JSON)
//!   GET    /pets/{id}            -> Pet | 404 Error
//!   DELETE /pets/{id}            -> 200 | 404 Error
//!   GET    /pets/{id}/toys       -> { items: Toy[] }
//!
//! Concurrency: per-request data lives in `wasi_http`'s per-task stack buffers;
//! the pet/toy data lives in a separate storage component (see
//! `src/memory_store.zig`) reached through the imported `example:petstore/store`
//! interface. `wabt component compose` links the two into one component.

const std = @import("std");
const http = @import("wasi_http");
// Generated by `wabt component bindgen` (the `store-consumer` world): typed
// `store.*` import wrappers + the `Pet` / `Toy` types. `store` is the interface
// namespace (`store.petCount()`, …); `Pet` is one of the module's types.
const store = @import("store").store;
const Pet = @import("store").Pet;

// ── JSON model types (serialized with std.json) ─────────────────────

const json_opts = std.json.Stringify.Options{ .emit_null_optional_fields = false };

/// Wire shape of a pet. `id` augments the TypeSpec `Pet` so clients can address
/// `/pets/{id}`; `tag` is omitted when absent (`emit_null_optional_fields`).
const PetJson = struct {
    id: i32,
    name: []const u8,
    tag: ?[]const u8 = null,
    age: i32,
};

const ToyJson = struct {
    id: i64,
    petId: i64,
    name: []const u8,
};

const ErrorJson = struct {
    code: i32,
    message: []const u8,
};

/// The `Pet` shape accepted by `POST /pets`.
const PetInput = struct {
    name: []const u8,
    tag: ?[]const u8 = null,
    age: i32,
};

fn petJson(p: Pet) PetJson {
    return .{ .id = @intCast(p.id), .name = p.name, .tag = p.tag, .age = @intCast(p.age) };
}

/// Serialize `value` as minified JSON into the response buffer via std.json.
fn writeJson(res: *http.Responder, value: anytype) void {
    res.print("{f}", .{std.json.fmt(value, json_opts)});
}

fn writeError(res: *http.Responder, status: u16, code: i32, message: []const u8) void {
    res.setStatus(status);
    writeJson(res, ErrorJson{ .code = code, .message = message });
}

// ── Handlers ────────────────────────────────────────────────────────

fn listPets(res: *http.Responder) void {
    var items: [128]PetJson = undefined;
    var n: usize = 0;
    const count = store.petCount();
    var i: u32 = 0;
    while (i < count and n < items.len) : (i += 1) {
        if (store.petAt(i)) |p| {
            items[n] = petJson(p);
            n += 1;
        }
    }
    writeJson(res, .{ .items = items[0..n] });
}

fn readPet(id: u32, res: *http.Responder) void {
    if (store.getPet(id)) |p| {
        writeJson(res, petJson(p));
    } else {
        writeError(res, 404, 404, "pet not found");
    }
}

fn deletePet(id: u32, res: *http.Responder) void {
    if (store.deletePet(id)) {
        writeJson(res, .{ .message = "deleted" });
    } else {
        writeError(res, 404, 404, "pet not found");
    }
}

fn listToys(pet_id: u32, res: *http.Responder) void {
    var items: [128]ToyJson = undefined;
    var n: usize = 0;
    const count = store.toyCount(pet_id);
    var i: u32 = 0;
    while (i < count and n < items.len) : (i += 1) {
        if (store.toyAt(pet_id, i)) |t| {
            items[n] = .{ .id = @intCast(t.id), .petId = @intCast(t.pet_id), .name = t.name };
            n += 1;
        }
    }
    writeJson(res, .{ .items = items[0..n] });
}

fn createPet(req: *const http.Request, res: *http.Responder) void {
    if (req.body.len == 0) return writeError(res, 400, 400, "request body required");
    var jbuf: [4096]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&jbuf);
    const parsed = std.json.parseFromSliceLeaky(PetInput, fba.allocator(), req.body, .{
        .ignore_unknown_fields = true,
    }) catch return writeError(res, 400, 400, "invalid pet json");
    if (parsed.age < 0 or parsed.age > 20) return writeError(res, 400, 400, "age must be 0..20");
    const p = store.createPet(parsed.name, parsed.tag, @intCast(parsed.age)) orelse
        return writeError(res, 507, 507, "store full");
    writeJson(res, petJson(p));
}

// ── Routing ─────────────────────────────────────────────────────────

fn handle(req: *const http.Request, res: *http.Responder) void {
    const q = std.mem.indexOfScalar(u8, req.path, '?');
    const path = if (q) |i| req.path[0..i] else req.path;

    if (std.mem.eql(u8, path, "/pets")) {
        switch (req.method) {
            .get => listPets(res),
            .post => createPet(req, res),
            else => writeError(res, 405, 405, "method not allowed"),
        }
        return;
    }

    if (std.mem.startsWith(u8, path, "/pets/")) {
        const rest = path["/pets/".len..];
        if (std.mem.indexOfScalar(u8, rest, '/')) |slash| {
            const id_str = rest[0..slash];
            const tail = rest[slash + 1 ..];
            if (std.mem.eql(u8, tail, "toys") and req.method == .get) {
                const pid = std.fmt.parseInt(u32, id_str, 10) catch return writeError(res, 400, 400, "invalid pet id");
                listToys(pid, res);
                return;
            }
            writeError(res, 404, 404, "not found");
            return;
        }
        const id = std.fmt.parseInt(u32, rest, 10) catch return writeError(res, 400, 400, "invalid pet id");
        switch (req.method) {
            .get => readPet(id, res),
            .delete => deletePet(id, res),
            else => writeError(res, 405, 405, "method not allowed"),
        }
        return;
    }

    writeError(res, 404, 404, "not found");
}

comptime {
    http.exportHandler(handle);
}
