//! Generated by `wabt component bindgen` from world `clocks-imports`. Do not edit.

const canon = @import("canon");
const abi = @import("abi");
const cm_async = @import("cm_async");

pub const Duration = u64;

pub const Mark = u64;

pub const Instant = struct {
    seconds: i64,
    nanoseconds: u32,
};

pub const monotonic_clock = struct {
    const imp = struct {
        extern "wasi:clocks/monotonic-clock@0.3.0" fn @"now"() i64;
        extern "wasi:clocks/monotonic-clock@0.3.0" fn @"get-resolution"() i64;
        extern "wasi:clocks/monotonic-clock@0.3.0" fn @"wait-until"(when: i64) i32;
        extern "wasi:clocks/monotonic-clock@0.3.0" fn @"wait-for"(how_long: i64) i32;
    };

    pub fn now() Mark {
        return canon.liftResultFlat(Mark, imp.@"now"());
    }
    pub fn getResolution() Duration {
        return canon.liftResultFlat(Duration, imp.@"get-resolution"());
    }
    pub fn waitUntil(when: Mark) void {
        const __status = imp.@"wait-until"(@bitCast(when));
        cm_async.awaitCall(__status);
    }
    pub fn waitFor(how_long: Duration) void {
        const __status = imp.@"wait-for"(@bitCast(how_long));
        cm_async.awaitCall(__status);
    }
};

pub const system_clock = struct {
    const imp = struct {
        extern "wasi:clocks/system-clock@0.3.0" fn @"now"(retptr: i32) void;
        extern "wasi:clocks/system-clock@0.3.0" fn @"get-resolution"() i64;
    };

    pub fn now() Instant {
        imp.@"now"(abi.retPtr());
        return canon.lift(Instant, abi.retArea());
    }
    pub fn getResolution() Duration {
        return canon.liftResultFlat(Duration, imp.@"get-resolution"());
    }
};

