//! Generated by `wabt component bindgen` from world `http-imports`. Do not edit.

const wit_types = @import("wit_types");

const canon = wit_types;
const abi = wit_types.abi;

pub const Duration = u64;

pub const Method = union(enum) {
    get,
    head,
    post,
    put,
    delete,
    connect,
    options,
    trace,
    patch,
    other: []const u8,
};

pub const Scheme = union(enum) {
    HTTP,
    HTTPS,
    other: []const u8,
};

pub const ErrorCode = union(enum) {
    DNS_timeout,
    DNS_error: DNSErrorPayload,
    destination_not_found,
    destination_unavailable,
    destination_IP_prohibited,
    destination_IP_unroutable,
    connection_refused,
    connection_terminated,
    connection_timeout,
    connection_read_timeout,
    connection_write_timeout,
    connection_limit_reached,
    TLS_protocol_error,
    TLS_certificate_error,
    TLS_alert_received: TLSAlertReceivedPayload,
    HTTP_request_denied,
    HTTP_request_length_required,
    HTTP_request_body_size: ?u64,
    HTTP_request_method_invalid,
    HTTP_request_URI_invalid,
    HTTP_request_URI_too_long,
    HTTP_request_header_section_size: ?u32,
    HTTP_request_header_size: ?FieldSizePayload,
    HTTP_request_trailer_section_size: ?u32,
    HTTP_request_trailer_size: FieldSizePayload,
    HTTP_response_incomplete,
    HTTP_response_header_section_size: ?u32,
    HTTP_response_header_size: FieldSizePayload,
    HTTP_response_body_size: ?u64,
    HTTP_response_trailer_section_size: ?u32,
    HTTP_response_trailer_size: FieldSizePayload,
    HTTP_response_transfer_coding: ?[]const u8,
    HTTP_response_content_coding: ?[]const u8,
    HTTP_response_timeout,
    HTTP_upgrade_failed,
    HTTP_protocol_error,
    loop_detected,
    configuration_error,
    internal_error: ?[]const u8,
};

pub const DNSErrorPayload = struct {
    rcode: ?[]const u8,
    info_code: ?u16,
};

pub const TLSAlertReceivedPayload = struct {
    alert_id: ?u8,
    alert_message: ?[]const u8,
};

pub const FieldSizePayload = struct {
    field_name: ?[]const u8,
    field_size: ?u32,
};

pub const HeaderError = union(enum) {
    invalid_syntax,
    forbidden,
    immutable,
    size_exceeded,
    other: ?[]const u8,
};

pub const RequestOptionsError = union(enum) {
    not_supported,
    immutable,
    other: ?[]const u8,
};

pub const FieldName = []const u8;

pub const FieldValue = []const u8;

pub const Fields = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:http/types@0.3.0" fn @"[constructor]fields"() i32;
        extern "wasi:http/types@0.3.0" fn @"[static]fields.from-list"(entries_ptr: i32, entries_len: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.get"(self: i32, name_ptr: i32, name_len: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.has"(self: i32, name_ptr: i32, name_len: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.set"(self: i32, name_ptr: i32, name_len: i32, value_ptr: i32, value_len: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.delete"(self: i32, name_ptr: i32, name_len: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.get-and-delete"(self: i32, name_ptr: i32, name_len: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.append"(self: i32, name_ptr: i32, name_len: i32, value_ptr: i32, value_len: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.copy-all"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]fields.clone"(self: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[resource-drop]fields"(self: i32) void;
    };

    pub fn init() Fields {
        return .{ .handle = imp.@"[constructor]fields"() };
    }
    pub fn fromList(entries: []const canon.Tuple(.{ FieldName, FieldValue })) canon.Result(Fields, HeaderError) {
        imp.@"[static]fields.from-list"(@intCast(@intFromPtr(entries.ptr)), @intCast(entries.len), abi.retPtr());
        return canon.lift(canon.Result(Fields, HeaderError), abi.retArea());
    }
    pub fn get(self: Fields, name: FieldName) []const FieldValue {
        imp.@"[method]fields.get"(self.handle, @intCast(@intFromPtr(name.ptr)), @intCast(name.len), abi.retPtr());
        return canon.lift([]const FieldValue, abi.retArea());
    }
    pub fn has(self: Fields, name: FieldName) bool {
        return canon.liftResultFlat(bool, imp.@"[method]fields.has"(self.handle, @intCast(@intFromPtr(name.ptr)), @intCast(name.len)));
    }
    pub fn set(self: Fields, name: FieldName, value: []const FieldValue) canon.Result(void, HeaderError) {
        imp.@"[method]fields.set"(self.handle, @intCast(@intFromPtr(name.ptr)), @intCast(name.len), @intCast(@intFromPtr(value.ptr)), @intCast(value.len), abi.retPtr());
        return canon.lift(canon.Result(void, HeaderError), abi.retArea());
    }
    pub fn delete(self: Fields, name: FieldName) canon.Result(void, HeaderError) {
        imp.@"[method]fields.delete"(self.handle, @intCast(@intFromPtr(name.ptr)), @intCast(name.len), abi.retPtr());
        return canon.lift(canon.Result(void, HeaderError), abi.retArea());
    }
    pub fn getAndDelete(self: Fields, name: FieldName) canon.Result([]const FieldValue, HeaderError) {
        imp.@"[method]fields.get-and-delete"(self.handle, @intCast(@intFromPtr(name.ptr)), @intCast(name.len), abi.retPtr());
        return canon.lift(canon.Result([]const FieldValue, HeaderError), abi.retArea());
    }
    pub fn append(self: Fields, name: FieldName, value: FieldValue) canon.Result(void, HeaderError) {
        imp.@"[method]fields.append"(self.handle, @intCast(@intFromPtr(name.ptr)), @intCast(name.len), @intCast(@intFromPtr(value.ptr)), @intCast(value.len), abi.retPtr());
        return canon.lift(canon.Result(void, HeaderError), abi.retArea());
    }
    pub fn copyAll(self: Fields) []const canon.Tuple(.{ FieldName, FieldValue }) {
        imp.@"[method]fields.copy-all"(self.handle, abi.retPtr());
        return canon.lift([]const canon.Tuple(.{ FieldName, FieldValue }), abi.retArea());
    }
    pub fn clone(self: Fields) Fields {
        return canon.liftResultFlat(Fields, imp.@"[method]fields.clone"(self.handle));
    }
    pub fn deinit(self: Fields) void {
        imp.@"[resource-drop]fields"(self.handle);
    }
};

pub const Headers = Fields;

pub const Trailers = Fields;

pub const Request = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:http/types@0.3.0" fn @"[static]request.new"(headers: i32, contents_disc: i32, contents: i32, trailers: i32, options_disc: i32, options: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request.get-method"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request.set-method"(self: i32, method_0: i32, method_1: i32, method_2: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]request.get-path-with-query"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request.set-path-with-query"(self: i32, path_with_query_disc: i32, path_with_query_ptr: i32, path_with_query_len: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]request.get-scheme"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request.set-scheme"(self: i32, scheme_disc: i32, scheme_0: i32, scheme_1: i32, scheme_2: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]request.get-authority"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request.set-authority"(self: i32, authority_disc: i32, authority_ptr: i32, authority_len: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]request.get-options"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request.get-headers"(self: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[static]request.consume-body"(this: i32, res: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[resource-drop]request"(self: i32) void;
    };

    pub fn new(headers: Headers, contents: ?canon.Stream(u8), trailers: __chan0, options: ?RequestOptions) canon.Tuple(.{ Request, __chan1 }) {
        const contents_disc: i32 = if (contents != null) 1 else 0;
        const contents_0: i32 = if (contents) |v| v.handle else 0;
        const options_disc: i32 = if (options != null) 1 else 0;
        const options_0: i32 = if (options) |v| v.handle else 0;
        imp.@"[static]request.new"(headers.handle, contents_disc, contents_0, trailers.handle, options_disc, options_0, abi.retPtr());
        return canon.lift(canon.Tuple(.{ Request, __chan1 }), abi.retArea());
    }
    pub fn getMethod(self: Request) Method {
        imp.@"[method]request.get-method"(self.handle, abi.retPtr());
        return canon.lift(Method, abi.retArea());
    }
    pub fn setMethod(self: Request, method: Method) canon.Result(void, void) {
        const method_s = canon.lowerFlat(Method, method, &abi.alloc);
        return canon.liftResultFlat(canon.Result(void, void), imp.@"[method]request.set-method"(self.handle, method_s[0], method_s[1], method_s[2]));
    }
    pub fn getPathWithQuery(self: Request) ?[]const u8 {
        imp.@"[method]request.get-path-with-query"(self.handle, abi.retPtr());
        return canon.lift(?[]const u8, abi.retArea());
    }
    pub fn setPathWithQuery(self: Request, path_with_query: ?[]const u8) canon.Result(void, void) {
        const path_with_query_disc: i32 = if (path_with_query != null) 1 else 0;
        const path_with_query_ptr: i32 = if (path_with_query) |v| @intCast(@intFromPtr(v.ptr)) else 0;
        const path_with_query_len: i32 = if (path_with_query) |v| @intCast(v.len) else 0;
        return canon.liftResultFlat(canon.Result(void, void), imp.@"[method]request.set-path-with-query"(self.handle, path_with_query_disc, path_with_query_ptr, path_with_query_len));
    }
    pub fn getScheme(self: Request) ?Scheme {
        imp.@"[method]request.get-scheme"(self.handle, abi.retPtr());
        return canon.lift(?Scheme, abi.retArea());
    }
    pub fn setScheme(self: Request, scheme: ?Scheme) canon.Result(void, void) {
        const scheme_s = canon.lowerFlat(?Scheme, scheme, &abi.alloc);
        return canon.liftResultFlat(canon.Result(void, void), imp.@"[method]request.set-scheme"(self.handle, scheme_s[0], scheme_s[1], scheme_s[2], scheme_s[3]));
    }
    pub fn getAuthority(self: Request) ?[]const u8 {
        imp.@"[method]request.get-authority"(self.handle, abi.retPtr());
        return canon.lift(?[]const u8, abi.retArea());
    }
    pub fn setAuthority(self: Request, authority: ?[]const u8) canon.Result(void, void) {
        const authority_disc: i32 = if (authority != null) 1 else 0;
        const authority_ptr: i32 = if (authority) |v| @intCast(@intFromPtr(v.ptr)) else 0;
        const authority_len: i32 = if (authority) |v| @intCast(v.len) else 0;
        return canon.liftResultFlat(canon.Result(void, void), imp.@"[method]request.set-authority"(self.handle, authority_disc, authority_ptr, authority_len));
    }
    pub fn getOptions(self: Request) ?RequestOptions {
        imp.@"[method]request.get-options"(self.handle, abi.retPtr());
        return canon.lift(?RequestOptions, abi.retArea());
    }
    pub fn getHeaders(self: Request) Headers {
        return canon.liftResultFlat(Headers, imp.@"[method]request.get-headers"(self.handle));
    }
    pub fn consumeBody(this: Request, res: __chan1) canon.Tuple(.{ canon.Stream(u8), __chan0 }) {
        imp.@"[static]request.consume-body"(this.handle, res.handle, abi.retPtr());
        return canon.lift(canon.Tuple(.{ canon.Stream(u8), __chan0 }), abi.retArea());
    }
    pub fn deinit(self: Request) void {
        imp.@"[resource-drop]request"(self.handle);
    }
};

pub const RequestOptions = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:http/types@0.3.0" fn @"[constructor]request-options"() i32;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.get-connect-timeout"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.set-connect-timeout"(self: i32, duration_disc: i32, duration: i64, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.get-first-byte-timeout"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.set-first-byte-timeout"(self: i32, duration_disc: i32, duration: i64, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.get-between-bytes-timeout"(self: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.set-between-bytes-timeout"(self: i32, duration_disc: i32, duration: i64, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]request-options.clone"(self: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[resource-drop]request-options"(self: i32) void;
    };

    pub fn init() RequestOptions {
        return .{ .handle = imp.@"[constructor]request-options"() };
    }
    pub fn getConnectTimeout(self: RequestOptions) ?Duration {
        imp.@"[method]request-options.get-connect-timeout"(self.handle, abi.retPtr());
        return canon.lift(?Duration, abi.retArea());
    }
    pub fn setConnectTimeout(self: RequestOptions, duration: ?Duration) canon.Result(void, RequestOptionsError) {
        const duration_disc: i32 = if (duration != null) 1 else 0;
        const duration_0: i64 = if (duration) |v| @bitCast(v) else 0;
        imp.@"[method]request-options.set-connect-timeout"(self.handle, duration_disc, duration_0, abi.retPtr());
        return canon.lift(canon.Result(void, RequestOptionsError), abi.retArea());
    }
    pub fn getFirstByteTimeout(self: RequestOptions) ?Duration {
        imp.@"[method]request-options.get-first-byte-timeout"(self.handle, abi.retPtr());
        return canon.lift(?Duration, abi.retArea());
    }
    pub fn setFirstByteTimeout(self: RequestOptions, duration: ?Duration) canon.Result(void, RequestOptionsError) {
        const duration_disc: i32 = if (duration != null) 1 else 0;
        const duration_0: i64 = if (duration) |v| @bitCast(v) else 0;
        imp.@"[method]request-options.set-first-byte-timeout"(self.handle, duration_disc, duration_0, abi.retPtr());
        return canon.lift(canon.Result(void, RequestOptionsError), abi.retArea());
    }
    pub fn getBetweenBytesTimeout(self: RequestOptions) ?Duration {
        imp.@"[method]request-options.get-between-bytes-timeout"(self.handle, abi.retPtr());
        return canon.lift(?Duration, abi.retArea());
    }
    pub fn setBetweenBytesTimeout(self: RequestOptions, duration: ?Duration) canon.Result(void, RequestOptionsError) {
        const duration_disc: i32 = if (duration != null) 1 else 0;
        const duration_0: i64 = if (duration) |v| @bitCast(v) else 0;
        imp.@"[method]request-options.set-between-bytes-timeout"(self.handle, duration_disc, duration_0, abi.retPtr());
        return canon.lift(canon.Result(void, RequestOptionsError), abi.retArea());
    }
    pub fn clone(self: RequestOptions) RequestOptions {
        return canon.liftResultFlat(RequestOptions, imp.@"[method]request-options.clone"(self.handle));
    }
    pub fn deinit(self: RequestOptions) void {
        imp.@"[resource-drop]request-options"(self.handle);
    }
};

pub const StatusCode = u16;

pub const Response = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:http/types@0.3.0" fn @"[static]response.new"(headers: i32, contents_disc: i32, contents: i32, trailers: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[method]response.get-status-code"(self: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]response.set-status-code"(self: i32, status_code: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[method]response.get-headers"(self: i32) i32;
        extern "wasi:http/types@0.3.0" fn @"[static]response.consume-body"(this: i32, res: i32, retptr: i32) void;
        extern "wasi:http/types@0.3.0" fn @"[resource-drop]response"(self: i32) void;
    };

    pub fn new(headers: Headers, contents: ?canon.Stream(u8), trailers: __chan0) canon.Tuple(.{ Response, __chan1 }) {
        const contents_disc: i32 = if (contents != null) 1 else 0;
        const contents_0: i32 = if (contents) |v| v.handle else 0;
        imp.@"[static]response.new"(headers.handle, contents_disc, contents_0, trailers.handle, abi.retPtr());
        return canon.lift(canon.Tuple(.{ Response, __chan1 }), abi.retArea());
    }
    pub fn getStatusCode(self: Response) StatusCode {
        return canon.liftResultFlat(StatusCode, imp.@"[method]response.get-status-code"(self.handle));
    }
    pub fn setStatusCode(self: Response, status_code: StatusCode) canon.Result(void, void) {
        return canon.liftResultFlat(canon.Result(void, void), imp.@"[method]response.set-status-code"(self.handle, @intCast(status_code)));
    }
    pub fn getHeaders(self: Response) Headers {
        return canon.liftResultFlat(Headers, imp.@"[method]response.get-headers"(self.handle));
    }
    pub fn consumeBody(this: Response, res: __chan1) canon.Tuple(.{ canon.Stream(u8), __chan0 }) {
        imp.@"[static]response.consume-body"(this.handle, res.handle, abi.retPtr());
        return canon.lift(canon.Tuple(.{ canon.Stream(u8), __chan0 }), abi.retArea());
    }
    pub fn deinit(self: Response) void {
        imp.@"[resource-drop]response"(self.handle);
    }
};

const __chan0 = canon.FutureOf(canon.Result(?Trailers, ErrorCode), "[future]wasi:http/types@0.3.0#[static]request.new#1");
const __chan1 = canon.FutureOf(canon.Result(void, ErrorCode), "[future]wasi:http/types@0.3.0#[static]request.new#2");

pub const types = struct {
    const imp = struct {};
};
