//! Generated by `wabt component bindgen` from world `random-imports`. Do not edit.

const canon = @import("canon");
const abi = @import("abi");

pub const random = struct {
    const imp = struct {
        extern "wasi:random/random@0.3.0" fn @"get-random-bytes"(max_len: i64, retptr: i32) void;
        extern "wasi:random/random@0.3.0" fn @"get-random-u64"() i64;
    };

    pub fn getRandomBytes(max_len: u64) []const u8 {
        imp.@"get-random-bytes"(@bitCast(max_len), abi.retPtr());
        return canon.lift([]const u8, abi.retArea());
    }
    pub fn getRandomU64() u64 {
        return canon.liftResultFlat(u64, imp.@"get-random-u64"());
    }
};

pub const insecure = struct {
    const imp = struct {
        extern "wasi:random/insecure@0.3.0" fn @"get-insecure-random-bytes"(max_len: i64, retptr: i32) void;
        extern "wasi:random/insecure@0.3.0" fn @"get-insecure-random-u64"() i64;
    };

    pub fn getInsecureRandomBytes(max_len: u64) []const u8 {
        imp.@"get-insecure-random-bytes"(@bitCast(max_len), abi.retPtr());
        return canon.lift([]const u8, abi.retArea());
    }
    pub fn getInsecureRandomU64() u64 {
        return canon.liftResultFlat(u64, imp.@"get-insecure-random-u64"());
    }
};

pub const insecure_seed = struct {
    const imp = struct {
        extern "wasi:random/insecure-seed@0.3.0" fn @"get-insecure-seed"(retptr: i32) void;
    };

    pub fn getInsecureSeed() canon.Tuple(.{ u64, u64 }) {
        imp.@"get-insecure-seed"(abi.retPtr());
        return canon.lift(canon.Tuple(.{ u64, u64 }), abi.retArea());
    }
};

