//! Generated by `wabt component bindgen` from world `cli-imports`. Do not edit.

const wit_types = @import("wit_types");

const canon = wit_types;
const abi = wit_types.abi;

pub const ErrorCode = enum {
    io,
    illegal_byte_sequence,
    pipe,
};

pub const TerminalInput = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:cli/terminal-input@0.3.0" fn @"[resource-drop]terminal-input"(self: i32) void;
    };

    pub fn deinit(self: TerminalInput) void {
        imp.@"[resource-drop]terminal-input"(self.handle);
    }
};

pub const TerminalOutput = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:cli/terminal-output@0.3.0" fn @"[resource-drop]terminal-output"(self: i32) void;
    };

    pub fn deinit(self: TerminalOutput) void {
        imp.@"[resource-drop]terminal-output"(self.handle);
    }
};

const __chan0 = canon.FutureOf(canon.Result(void, ErrorCode), "[future]wasi:cli/stdin@0.3.0#read-via-stream#1");
const __chan1 = canon.FutureOf(canon.Result(void, ErrorCode), "[future]wasi:cli/stdout@0.3.0#write-via-stream#1");
const __chan2 = canon.FutureOf(canon.Result(void, ErrorCode), "[future]wasi:cli/stderr@0.3.0#write-via-stream#1");

pub const environment = struct {
    const imp = struct {
        extern "wasi:cli/environment@0.3.0" fn @"get-environment"(retptr: i32) void;
        extern "wasi:cli/environment@0.3.0" fn @"get-arguments"(retptr: i32) void;
        extern "wasi:cli/environment@0.3.0" fn @"get-initial-cwd"(retptr: i32) void;
    };

    pub fn getEnvironment() []const canon.Tuple(.{ []const u8, []const u8 }) {
        imp.@"get-environment"(abi.retPtr());
        return canon.lift([]const canon.Tuple(.{ []const u8, []const u8 }), abi.retArea());
    }
    pub fn getArguments() []const []const u8 {
        imp.@"get-arguments"(abi.retPtr());
        return canon.lift([]const []const u8, abi.retArea());
    }
    pub fn getInitialCwd() ?[]const u8 {
        imp.@"get-initial-cwd"(abi.retPtr());
        return canon.lift(?[]const u8, abi.retArea());
    }
};

pub const exit = struct {
    const imp = struct {
        extern "wasi:cli/exit@0.3.0" fn exit(status: i32) void;
        extern "wasi:cli/exit@0.3.0" fn @"exit-with-code"(status_code: i32) void;
    };

    pub fn exit(status: canon.Result(void, void)) void {
        const status_s = canon.lowerFlat(canon.Result(void, void), status, &abi.alloc);
        imp.exit(status_s[0]);
    }
    pub fn exitWithCode(status_code: u8) void {
        imp.@"exit-with-code"(@intCast(status_code));
    }
};

pub const stdin = struct {
    const imp = struct {
        extern "wasi:cli/stdin@0.3.0" fn @"read-via-stream"(retptr: i32) void;
    };

    pub fn readViaStream() canon.Tuple(.{ canon.Stream(u8), __chan0 }) {
        imp.@"read-via-stream"(abi.retPtr());
        return canon.lift(canon.Tuple(.{ canon.Stream(u8), __chan0 }), abi.retArea());
    }
};

pub const stdout = struct {
    const imp = struct {
        extern "wasi:cli/stdout@0.3.0" fn @"write-via-stream"(data: i32) i32;
    };

    pub fn writeViaStream(data: canon.Stream(u8)) __chan1 {
        return canon.liftResultFlat(__chan1, imp.@"write-via-stream"(data.handle));
    }
};

pub const stderr = struct {
    const imp = struct {
        extern "wasi:cli/stderr@0.3.0" fn @"write-via-stream"(data: i32) i32;
    };

    pub fn writeViaStream(data: canon.Stream(u8)) __chan2 {
        return canon.liftResultFlat(__chan2, imp.@"write-via-stream"(data.handle));
    }
};

pub const terminal_input = struct {
    const imp = struct {};
};

pub const terminal_output = struct {
    const imp = struct {};
};

pub const terminal_stdin = struct {
    const imp = struct {
        extern "wasi:cli/terminal-stdin@0.3.0" fn @"get-terminal-stdin"(retptr: i32) void;
    };

    pub fn getTerminalStdin() ?TerminalInput {
        imp.@"get-terminal-stdin"(abi.retPtr());
        return canon.lift(?TerminalInput, abi.retArea());
    }
};

pub const terminal_stdout = struct {
    const imp = struct {
        extern "wasi:cli/terminal-stdout@0.3.0" fn @"get-terminal-stdout"(retptr: i32) void;
    };

    pub fn getTerminalStdout() ?TerminalOutput {
        imp.@"get-terminal-stdout"(abi.retPtr());
        return canon.lift(?TerminalOutput, abi.retArea());
    }
};

pub const terminal_stderr = struct {
    const imp = struct {
        extern "wasi:cli/terminal-stderr@0.3.0" fn @"get-terminal-stderr"(retptr: i32) void;
    };

    pub fn getTerminalStderr() ?TerminalOutput {
        imp.@"get-terminal-stderr"(abi.retPtr());
        return canon.lift(?TerminalOutput, abi.retArea());
    }
};
