//! Generated by `wabt component bindgen` from world `random-imports`. Do not edit.

const wit_types = @import("wit_types");

pub const random = struct {
    const imp = struct {
        extern "wasi:random/random@0.3.0" fn @"get-random-bytes"(max_len: i64, retptr: i32) void;
        extern "wasi:random/random@0.3.0" fn @"get-random-u64"() i64;
    };

    pub fn getRandomBytes(max_len: u64) []const u8 {
        imp.@"get-random-bytes"(@bitCast(max_len), wit_types.retPtr());
        return wit_types.lift([]const u8, wit_types.retArea());
    }
    pub fn getRandomU64() u64 {
        return wit_types.liftResultFlat(u64, imp.@"get-random-u64"());
    }
};

pub const insecure = struct {
    const imp = struct {
        extern "wasi:random/insecure@0.3.0" fn @"get-insecure-random-bytes"(max_len: i64, retptr: i32) void;
        extern "wasi:random/insecure@0.3.0" fn @"get-insecure-random-u64"() i64;
    };

    pub fn getInsecureRandomBytes(max_len: u64) []const u8 {
        imp.@"get-insecure-random-bytes"(@bitCast(max_len), wit_types.retPtr());
        return wit_types.lift([]const u8, wit_types.retArea());
    }
    pub fn getInsecureRandomU64() u64 {
        return wit_types.liftResultFlat(u64, imp.@"get-insecure-random-u64"());
    }
};

pub const insecure_seed = struct {
    const imp = struct {
        extern "wasi:random/insecure-seed@0.3.0" fn @"get-insecure-seed"(retptr: i32) void;
    };

    pub fn getInsecureSeed() wit_types.Tuple(.{ u64, u64 }) {
        imp.@"get-insecure-seed"(wit_types.retPtr());
        return wit_types.lift(wit_types.Tuple(.{ u64, u64 }), wit_types.retArea());
    }
};

