//! Generated by `wabt component bindgen` from world `fs-imports`. Do not edit.

const wit_types = @import("wit_types");
const wit_async = @import("wit_async");

pub const Instant = struct {
    seconds: i64,
    nanoseconds: u32,
};

pub const Filesize = u64;

pub const DescriptorType = union(enum) {
    block_device,
    character_device,
    directory,
    fifo,
    symbolic_link,
    regular_file,
    socket,
    other: ?[]const u8,
};

pub const DescriptorFlags = packed struct(u8) {
    read: bool = false,
    write: bool = false,
    file_integrity_sync: bool = false,
    data_integrity_sync: bool = false,
    requested_write_sync: bool = false,
    mutate_directory: bool = false,
    _padding: u2 = 0,
};

pub const DescriptorStat = struct {
    type: DescriptorType,
    link_count: LinkCount,
    size: Filesize,
    data_access_timestamp: ?Instant,
    data_modification_timestamp: ?Instant,
    status_change_timestamp: ?Instant,
};

pub const PathFlags = packed struct(u8) {
    symlink_follow: bool = false,
    _padding: u7 = 0,
};

pub const OpenFlags = packed struct(u8) {
    create: bool = false,
    directory: bool = false,
    exclusive: bool = false,
    truncate: bool = false,
    _padding: u4 = 0,
};

pub const LinkCount = u64;

pub const NewTimestamp = union(enum) {
    no_change,
    now,
    timestamp: Instant,
};

pub const DirectoryEntry = struct {
    type: DescriptorType,
    name: []const u8,
};

pub const ErrorCode = union(enum) {
    access,
    already,
    bad_descriptor,
    busy,
    deadlock,
    quota,
    exist,
    file_too_large,
    illegal_byte_sequence,
    in_progress,
    interrupted,
    invalid,
    io,
    is_directory,
    loop,
    too_many_links,
    message_size,
    name_too_long,
    no_device,
    no_entry,
    no_lock,
    insufficient_memory,
    insufficient_space,
    not_directory,
    not_empty,
    not_recoverable,
    unsupported,
    no_tty,
    no_such_device,
    overflow,
    not_permitted,
    pipe,
    read_only,
    invalid_seek,
    text_file_busy,
    cross_device,
    other: ?[]const u8,
};

pub const Advice = enum {
    normal,
    sequential,
    random,
    will_need,
    dont_need,
    no_reuse,
};

pub const MetadataHashValue = struct {
    lower: u64,
    upper: u64,
};

pub const Descriptor = struct {
    handle: i32,

    const imp = struct {
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.read-via-stream"(self: i32, offset: i64, retptr: i32) void;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.write-via-stream"(self: i32, data: i32, offset: i64) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.append-via-stream"(self: i32, data: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.advise"(self: i32, offset: i64, length: i64, advice: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.sync-data"(self: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.get-flags"(self: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.get-type"(self: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.set-size"(self: i32, size: i64, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.set-times"(args_ptr: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.read-directory"(self: i32, retptr: i32) void;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.sync"(self: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.create-directory-at"(self: i32, path_ptr: i32, path_len: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.stat"(self: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.stat-at"(self: i32, path_flags: i32, path_ptr: i32, path_len: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.set-times-at"(args_ptr: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.link-at"(args_ptr: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.open-at"(args_ptr: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.readlink-at"(self: i32, path_ptr: i32, path_len: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.remove-directory-at"(self: i32, path_ptr: i32, path_len: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.rename-at"(args_ptr: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.symlink-at"(args_ptr: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.unlink-file-at"(self: i32, path_ptr: i32, path_len: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.is-same-object"(self: i32, other: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.metadata-hash"(self: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[method]descriptor.metadata-hash-at"(self: i32, path_flags: i32, path_ptr: i32, path_len: i32, result_ptr: i32) i32;
        extern "wasi:filesystem/types@0.3.0" fn @"[resource-drop]descriptor"(self: i32) void;
    };

    pub fn readViaStream(self: Descriptor, offset: Filesize) wit_types.Tuple(.{ wit_types.Stream(u8), __chan0 }) {
        imp.@"[method]descriptor.read-via-stream"(self.handle, @bitCast(offset), wit_types.retPtr());
        return wit_types.lift(wit_types.Tuple(.{ wit_types.Stream(u8), __chan0 }), wit_types.retArea());
    }
    pub fn writeViaStream(self: Descriptor, data: wit_types.Stream(u8), offset: Filesize) __chan0 {
        return wit_types.liftResultFlat(__chan0, imp.@"[method]descriptor.write-via-stream"(self.handle, data.handle, @bitCast(offset)));
    }
    pub fn appendViaStream(self: Descriptor, data: wit_types.Stream(u8)) __chan0 {
        return wit_types.liftResultFlat(__chan0, imp.@"[method]descriptor.append-via-stream"(self.handle, data.handle));
    }
    pub fn advise(self: Descriptor, offset: Filesize, length: Filesize, advice: Advice) wit_types.Result(void, ErrorCode) {
        const advice_s = wit_types.lowerFlat(Advice, advice, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.advise"(self.handle, @bitCast(offset), @bitCast(length), advice_s[0], wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn syncData(self: Descriptor) wit_types.Result(void, ErrorCode) {
        const __status = imp.@"[method]descriptor.sync-data"(self.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn getFlags(self: Descriptor) wit_types.Result(DescriptorFlags, ErrorCode) {
        const __status = imp.@"[method]descriptor.get-flags"(self.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(DescriptorFlags, ErrorCode), wit_types.retArea());
    }
    pub fn getType(self: Descriptor) wit_types.Result(DescriptorType, ErrorCode) {
        const __status = imp.@"[method]descriptor.get-type"(self.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(DescriptorType, ErrorCode), wit_types.retArea());
    }
    pub fn setSize(self: Descriptor, size: Filesize) wit_types.Result(void, ErrorCode) {
        const __status = imp.@"[method]descriptor.set-size"(self.handle, @bitCast(size), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn setTimes(self: Descriptor, data_access_timestamp: NewTimestamp, data_modification_timestamp: NewTimestamp) wit_types.Result(void, ErrorCode) {
        const __pargs = .{ self, data_access_timestamp, data_modification_timestamp };
        const __pp = wit_types.alloc(wit_types.sizeOf(@TypeOf(__pargs)), wit_types.alignOf(@TypeOf(__pargs)));
        wit_types.lower(@TypeOf(__pargs), __pargs, __pp, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.set-times"(@intCast(@intFromPtr(__pp)), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn readDirectory(self: Descriptor) wit_types.Tuple(.{ __chan1, __chan0 }) {
        imp.@"[method]descriptor.read-directory"(self.handle, wit_types.retPtr());
        return wit_types.lift(wit_types.Tuple(.{ __chan1, __chan0 }), wit_types.retArea());
    }
    pub fn sync(self: Descriptor) wit_types.Result(void, ErrorCode) {
        const __status = imp.@"[method]descriptor.sync"(self.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn createDirectoryAt(self: Descriptor, path: []const u8) wit_types.Result(void, ErrorCode) {
        const __status = imp.@"[method]descriptor.create-directory-at"(self.handle, @intCast(@intFromPtr(path.ptr)), @intCast(path.len), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn stat(self: Descriptor) wit_types.Result(DescriptorStat, ErrorCode) {
        const __status = imp.@"[method]descriptor.stat"(self.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(DescriptorStat, ErrorCode), wit_types.retArea());
    }
    pub fn statAt(self: Descriptor, path_flags: PathFlags, path: []const u8) wit_types.Result(DescriptorStat, ErrorCode) {
        const path_flags_s = wit_types.lowerFlat(PathFlags, path_flags, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.stat-at"(self.handle, path_flags_s[0], @intCast(@intFromPtr(path.ptr)), @intCast(path.len), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(DescriptorStat, ErrorCode), wit_types.retArea());
    }
    pub fn setTimesAt(self: Descriptor, path_flags: PathFlags, path: []const u8, data_access_timestamp: NewTimestamp, data_modification_timestamp: NewTimestamp) wit_types.Result(void, ErrorCode) {
        const __pargs = .{ self, path_flags, path, data_access_timestamp, data_modification_timestamp };
        const __pp = wit_types.alloc(wit_types.sizeOf(@TypeOf(__pargs)), wit_types.alignOf(@TypeOf(__pargs)));
        wit_types.lower(@TypeOf(__pargs), __pargs, __pp, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.set-times-at"(@intCast(@intFromPtr(__pp)), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn linkAt(self: Descriptor, old_path_flags: PathFlags, old_path: []const u8, new_descriptor: Descriptor, new_path: []const u8) wit_types.Result(void, ErrorCode) {
        const __pargs = .{ self, old_path_flags, old_path, new_descriptor, new_path };
        const __pp = wit_types.alloc(wit_types.sizeOf(@TypeOf(__pargs)), wit_types.alignOf(@TypeOf(__pargs)));
        wit_types.lower(@TypeOf(__pargs), __pargs, __pp, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.link-at"(@intCast(@intFromPtr(__pp)), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn openAt(self: Descriptor, path_flags: PathFlags, path: []const u8, open_flags: OpenFlags, flags: DescriptorFlags) wit_types.Result(Descriptor, ErrorCode) {
        const __pargs = .{ self, path_flags, path, open_flags, flags };
        const __pp = wit_types.alloc(wit_types.sizeOf(@TypeOf(__pargs)), wit_types.alignOf(@TypeOf(__pargs)));
        wit_types.lower(@TypeOf(__pargs), __pargs, __pp, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.open-at"(@intCast(@intFromPtr(__pp)), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(Descriptor, ErrorCode), wit_types.retArea());
    }
    pub fn readlinkAt(self: Descriptor, path: []const u8) wit_types.Result([]const u8, ErrorCode) {
        const __status = imp.@"[method]descriptor.readlink-at"(self.handle, @intCast(@intFromPtr(path.ptr)), @intCast(path.len), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result([]const u8, ErrorCode), wit_types.retArea());
    }
    pub fn removeDirectoryAt(self: Descriptor, path: []const u8) wit_types.Result(void, ErrorCode) {
        const __status = imp.@"[method]descriptor.remove-directory-at"(self.handle, @intCast(@intFromPtr(path.ptr)), @intCast(path.len), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn renameAt(self: Descriptor, old_path: []const u8, new_descriptor: Descriptor, new_path: []const u8) wit_types.Result(void, ErrorCode) {
        const __pargs = .{ self, old_path, new_descriptor, new_path };
        const __pp = wit_types.alloc(wit_types.sizeOf(@TypeOf(__pargs)), wit_types.alignOf(@TypeOf(__pargs)));
        wit_types.lower(@TypeOf(__pargs), __pargs, __pp, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.rename-at"(@intCast(@intFromPtr(__pp)), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn symlinkAt(self: Descriptor, old_path: []const u8, new_path: []const u8) wit_types.Result(void, ErrorCode) {
        const __pargs = .{ self, old_path, new_path };
        const __pp = wit_types.alloc(wit_types.sizeOf(@TypeOf(__pargs)), wit_types.alignOf(@TypeOf(__pargs)));
        wit_types.lower(@TypeOf(__pargs), __pargs, __pp, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.symlink-at"(@intCast(@intFromPtr(__pp)), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn unlinkFileAt(self: Descriptor, path: []const u8) wit_types.Result(void, ErrorCode) {
        const __status = imp.@"[method]descriptor.unlink-file-at"(self.handle, @intCast(@intFromPtr(path.ptr)), @intCast(path.len), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(void, ErrorCode), wit_types.retArea());
    }
    pub fn isSameObject(self: Descriptor, other: Descriptor) bool {
        const __status = imp.@"[method]descriptor.is-same-object"(self.handle, other.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(bool, wit_types.retArea());
    }
    pub fn metadataHash(self: Descriptor) wit_types.Result(MetadataHashValue, ErrorCode) {
        const __status = imp.@"[method]descriptor.metadata-hash"(self.handle, wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(MetadataHashValue, ErrorCode), wit_types.retArea());
    }
    pub fn metadataHashAt(self: Descriptor, path_flags: PathFlags, path: []const u8) wit_types.Result(MetadataHashValue, ErrorCode) {
        const path_flags_s = wit_types.lowerFlat(PathFlags, path_flags, &wit_types.alloc);
        const __status = imp.@"[method]descriptor.metadata-hash-at"(self.handle, path_flags_s[0], @intCast(@intFromPtr(path.ptr)), @intCast(path.len), wit_types.retPtr());
        wit_async.awaitCall(__status);
        return wit_types.lift(wit_types.Result(MetadataHashValue, ErrorCode), wit_types.retArea());
    }
    pub fn deinit(self: Descriptor) void {
        imp.@"[resource-drop]descriptor"(self.handle);
    }
};

const __chan0 = wit_types.FutureOf(wit_types.Result(void, ErrorCode), "[future]wasi:filesystem/types@0.3.0#[method]descriptor.read-via-stream#1");
const __chan1 = wit_types.StreamOf(DirectoryEntry, "[stream]wasi:filesystem/types@0.3.0#[method]descriptor.read-directory#0");

pub const types = struct {
    const imp = struct {
    };

};

pub const preopens = struct {
    const imp = struct {
        extern "wasi:filesystem/preopens@0.3.0" fn @"get-directories"(retptr: i32) void;
    };

    pub fn getDirectories() []const wit_types.Tuple(.{ Descriptor, []const u8 }) {
        imp.@"get-directories"(wit_types.retPtr());
        return wit_types.lift([]const wit_types.Tuple(.{ Descriptor, []const u8 }), wit_types.retArea());
    }
};

