const std = @import("std");
const wabt = @import("wabt");

/// Read a WebAssembly binary and produce a C source stub.
pub fn wasmToC(allocator: std.mem.Allocator, wasm_bytes: []const u8) ![]u8 {
    var module = try wabt.binary.reader.readModule(allocator, wasm_bytes);
    defer module.deinit();

    const name = module.name orelse "module";

    return std.fmt.allocPrint(allocator,
        \\/* Generated by wasm2c */
        \\#ifndef WASM2C_{s}_H
        \\#define WASM2C_{s}_H
        \\
        \\#include <stdint.h>
        \\#include <stdlib.h>
        \\
        \\/* Module: {s} */
        \\/* Functions: {d} */
        \\/* Memories:  {d} */
        \\/* Tables:    {d} */
        \\/* Globals:   {d} */
        \\/* Exports:   {d} */
        \\
        \\void {s}_init(void);
        \\void {s}_free(void);
        \\
        \\#endif
        \\
    , .{
        name, name,
        name,
        module.funcs.items.len,
        module.memories.items.len,
        module.tables.items.len,
        module.globals.items.len,
        module.exports.items.len,
        name, name,
    });
}

pub fn main() void {
    std.debug.print(
        \\wasm2c — translate WebAssembly binary to C source
        \\
        \\Usage: wasm2c [options] <file>
        \\
        \\  -o, --output <file>   Output C file
        \\  -n, --module-name     Module name (default: derived from filename)
        \\
    , .{});
}

test "empty module produces C header" {
    const empty_wasm = &[_]u8{ 0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00 };
    const output = try wasmToC(std.testing.allocator, empty_wasm);
    defer std.testing.allocator.free(output);
    try std.testing.expect(std.mem.indexOf(u8, output, "Generated by wasm2c") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "#ifndef") != null);
}
