const std = @import("std");
const wabt = @import("wabt");

/// Read a WebAssembly binary and produce a C header via CWriter.
pub fn wasmToC(allocator: std.mem.Allocator, wasm_bytes: []const u8) ![]u8 {
    var module = try wabt.binary.reader.readModule(allocator, wasm_bytes);
    defer module.deinit();
    return wabt.CWriter.writeHeader(allocator, &module, "w2c");
}

pub fn main() void {
    std.debug.print(
        \\wasm2c — translate WebAssembly binary to C source
        \\
        \\Usage: wasm2c [options] <file>
        \\
        \\  -o, --output <file>   Output C file
        \\  -n, --module-name     Module name (default: derived from filename)
        \\
    , .{});
}

test "empty module produces C header" {
    const empty_wasm = &[_]u8{ 0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00 };
    const output = try wasmToC(std.testing.allocator, empty_wasm);
    defer std.testing.allocator.free(output);
    try std.testing.expect(std.mem.indexOf(u8, output, "Generated by wabt-zig") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "#ifndef") != null);
}
